### ISSUE TITLE
will this app have new version ?

### ISSUE THREAD

**Issue by TristenChenTao** [luin/medis#121]
will this app have new version ?

**Comment by aprisniak** [comment]
The same question.

**Comment by Beenhakker** [comment]
Indeed. Seeing lots of old stuff when building this app. Bit harsh to have people pay for an outdated app / app that will expire...

npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated conventional-changelog@0.5.3: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

**Comment by Beenhakker** [comment]
> It looks like this app is no longer available in the MacOS store on latest MacOS. :( Any plans for a refresh?

It was probably removed by Apple, since it was insecure / outdated, or the developers did them themselves.

You can simply download the source, and use the build steps (npm) to install it.

**Comment by luin** [comment]
Sorry for the late response. Medis 2 was released several months ago and is under active development. Feel free to upgrade and try it out: https://getmedis.com
