### ISSUE TITLE
"SSH Error: All configured authentication methods failed" when connecting via SSH tunnel

### ISSUE THREAD

**Issue by Egoscio** [luin/medis#13]
Hello,

I'm trying to connect to my remote Redis DB via the tunneling option, but I keep encountering this error: "SSH Error: All configured authentication methods failed".
I can confirm that my configuration is correct, as I just tried connecting to my database via ssh and redis-cli. I was even able to connect to it via Medis without tunneling. Any idea how I can troubleshoot this?

Thanks,

- Egoscio

**Comment by luin** [comment]
It's either because the SSH password you provided is wrong, or the SSH private key you provided is invalid. Notice that Medis won't look for the default SSH private key path (`~/.ssh`), so you have to specified one explicitly.

Here's an example:

![image](https://cloud.githubusercontent.com/assets/635902/12707834/db0a9fb0-c8d3-11e5-8e90-2cea95ccecbe.png)

**Comment by Egoscio** [comment]
That's strange. I provided it with the password, which functions correctly whenever I connect via SSH on my Terminal. I even tried to reconnect at least 5 times but it still doesn't work. What's even weirder is that the release I downloaded from your prebuilt page doesn't look like the screenshot you posted above.
![screen shot 2016-01-31 at 7 48 22 pm](https://cloud.githubusercontent.com/assets/3950951/12708373/a3347a96-c853-11e5-832f-33cad0a91c20.png)
(Notice that there is no SSH Key or SSH Key Passphrase, instead there is a SSH Password)

**Comment by luin** [comment]
Well, I just confirmed it's a bug that Medis currently only supports login with SSH key instead of SSH password. Looks like people all use ssh keys to login to their servers :crying_cat_face: 

BTW, "SSH Key" will show when you click the "key" button on the right side of the "SSH Password" row.

I'll release a new version later today.

**Comment by Egoscio** [comment]
Thank you! Other than that, I'm in love with Medis :)

**Comment by kortemy** [comment]
Sorry to necro this issue, but I am having a similar problem.

When I press the key icon and select my key, the field doesn't change to "SSH key", it stays "SSH password" and is empty. Connection fails.

This is using latest version (1.0.3-1) on Arch Linux, installed via AUR package.
