### ISSUE TITLE
how to connect to redis-server? what  is the right url ? 

### ISSUE THREAD

**Issue by kavinbj** [luin/medis#254]
how to connect to redis-server? what  is the right url ? 

for example：
test1:
![image](https://user-images.githubusercontent.com/9006416/159154317-875ebb99-531e-49f9-928e-35ac623f4fa4.png)
result error
![image](https://user-images.githubusercontent.com/9006416/159154346-7eb3d8e7-97da-460f-83c0-d18c343063de.png)

test2:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/9006416/159154388-a52f3863-d78c-4d9d-9907-47490cec8b09.png">
result error
<img width="315" alt="image" src="https://user-images.githubusercontent.com/9006416/159154420-88908071-a121-4f26-8818-9c3c1804e963.png">

**Comment by luin** [comment]
Hey @kavinbj 👋 

You should use `127.0.0.1` for the host field. The error in the last screenshot was caused by the server requiring a password. You need to create a new connection and fill the password field:

![CleanShot 2022-03-20 at 17 19 23@2x](https://user-images.githubusercontent.com/635902/159155922-b714a343-665e-4ca2-88ff-f7e345c0063a.png)

**Comment by kavinbj** [comment]
thanks! I get it
