### ISSUE TITLE
Update about the business model

### ISSUE THREAD

**Issue by FabienDeborde** [luin/medis#275]
I just opened medis after a week or so, now 80% of my saved redis connection are gone and I am on a "free trial"....
I had no idea medis went the "freemium" way and it would have been nice to have a proper announcement. 

I might have missed it but I couldn't find anything on your GitHub readme nor your Twitter page.

Now on your official page it is written:
>**What are the limitations of the free trial?**
>*We may change the limitations without any notifications in the future releases.*

Could you please state where you are going with your application?
Is it going to stay freemium or do you have other plans for the future?

I really like your app, and will probably pay for the "real" version, but before that I really would like to know if this is gonna be a "lifetime" license where you pay for a new version every year anyway, or is it going to be a SaaS in 2 months and the licenses will become useless.

**Comment by luin** [comment]
Hey @FabienDeborde 👋 , Thanks for using Medis!

> now 80% of my saved redis connection are gone

Sorry for the trouble! Medis 2 should not delete users' connections even when they are on a free trial so I'm not sure what happened. Could it be possible that you are using two versions of Medis 2, one of which was downloaded from the App Store and the other from https://getmedis.com? Because they don't share the connection data due to sandbox limits.

> Could you please state where you are going with your application?

The current limitations can be found on https://getmedis.com/pricing, and yes Medis 2 will stay freemium so you can use Medis 2 without any payments. Some features are limited though.

The license is a one-time payment and there won't be new versions that you need to purchase every year, which means you pay once and enjoy the updates lifetime. As more new features are added to Medis 2, the price may be increased to support Medis 2's further development but that won't affect existing customers.

Let me know if there is anything unclear.

**Comment by FabienDeborde** [comment]
Hey @luin !
Thanks a lot for you quick answer! 🙇‍♂️ 

I am so sorry, you are totally right. I just checked and had a version installed by Brew and the other (the one I used this morning) installed by the AppStore...

I am really glad to hear the direction you chose for your application!
Once I am done with my work today, I will migrate my connections to the version 2 and upgrade to the full version.
