### ISSUE TITLE
Connection reset (SSH tunnel)

### ISSUE THREAD

**Issue by DiegoRBaquero** [luin/medis#284]
Hello!

I recently came back to using medis (Paid medis 1 through app store) and found about Medis 2! So downloaded that instead.

But I can't really connect to redis through an SSH tunnel.

I get "Connection reset"
<img width="861" alt="image" src="https://user-images.githubusercontent.com/2006839/217566771-aa993af5-9852-4e8b-96ce-237027f7a21e.png">

Settings: 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/2006839/217567135-5dbdb2f2-a320-4619-9072-a887fa63e8ef.png">

But no logs or anything (the ssh logs for example are great to debug)

What could be happening?

I can ssh into the server and use redis-cli, no user, no password, no ssl, nothing but the default installation.

Confirmed running
`tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN`

I tried switching localhost for 127.0.0.1

Can't really figure why it would fail 🤔 

Any help is appreciated.

On a side note: already asked my company if I can purchase the license through my app store account and get reimbursed 🙌🏼

**Comment by DiegoRBaquero** [comment]
@luin pinging, this issue is blocking me from purchasing.

**Comment by luin** [comment]
Hey @DiegoRBaquero 👋,

Sorry for the late response! Not sure why I overlooked the issue. Have you tried specifying your SSH file: https://docs.getmedis.com/settings/custom-ssh-config? By default, Medis doesn't use your SSH file so that could be a reason. Besides that, can you also try setting up an SSH port forwarding locally https://medium.com/momologic/connecting-to-redis-via-ssh-tunneling-f41c3d2ee988 and connect to the server on Medis in a standalone mode?

**Comment by DiegoRBaquero** [comment]
Creating the tunnel through ssh myself and testing standalone pointed out the issued:

`channel 3: open failed: administratively prohibited: open failed`

SSH config had `AllowTcpForwarding no`, switching it to `AllowTcpForwarding yes` and restarting ssh server solved the issue.

I've purchased the license btw <3
