### ISSUE TITLE
Can't see any of my keys on the sidebar

### ISSUE THREAD

**Issue by pazaricha** [luin/medis#3]
Hi :)

First of thanks for creating this! I bought it from the Mac App store to support you and the project.

Unforunallty after downloading and installing I can't see any of my keys on the "keys sidebar" not even when I search for "*".

What am I doing wrong here?

<img width="823" alt="screen shot 2016-01-12 at 9 57 53 am" src="https://cloud.githubusercontent.com/assets/1285305/12259876/27f19cf6-b921-11e5-8dda-71e506fc53f6.png">

<img width="963" alt="screen shot 2016-01-12 at 11 38 50 am" src="https://cloud.githubusercontent.com/assets/1285305/12259879/2c4e0bb8-b921-11e5-9081-00813af41cc9.png">

**Comment by luin** [comment]
Thank you for buying Medis! :laughing: 
Medis only supports Redis >= 2.8 version because `scan` command is introduced since 2.8. `scan` is very useful to get key list without blocking the server, which is crucial in the production environment. Because the latest stable is 3.0 and 2.6 is a very old version, Medis doesn't support it at this time.

The version is checked here: https://github.com/luin/medis/blob/master/client/actions.js#L78-L86 and it'll show a alter window to notice the version is not supported. That's strange that you didn't see it. I'll definitely look into it.

**Comment by pazaricha** [comment]
Thanks! 
I upgraded redis and it indeed solved ths issue. 

:100:

**Comment by shiny** [comment]
@luin Suggest to update README.md for the condition `Redis >= 2.8`
