### ISSUE TITLE
Could not change DB

### ISSUE THREAD

**Issue by dinowang** [luin/medis#33]
I discover Medis provide a dropdown for changing DB. But it can not work (with no any selectable option). Does some one had same situation?

![image](https://cloud.githubusercontent.com/assets/3980212/16755764/8b2a18b6-4832-11e6-96f1-a6204c995209.png)

**Comment by luin** [comment]
Are you connecting a SaaS Redis service? Which version are you using?

**Comment by jotich** [comment]
I am having the same issue as well. DB selection is empty and clicking on it doesn't do anything. There's more than 1 DB but it looks like it's just showing the key/values for DB 0.

I'm connecting to an AWS Elasticache (Redis 2.8.24) instance using SSH tunneling. Running Medis on OS X 10.11.6.

**Comment by luin** [comment]
@jotich It seems AWS Elasticache doesn't support `INFO` command so that we can't know how many databases are available. A workaround is to switch to the "Terminal" tab and invoke `select 1` ("1" is which database you want to switch to).

**Comment by jotich** [comment]
@luin Thanks for your response. The workaround is just what I needed, until there's a better solution. Thanks again for this project!

**Comment by roeyby** [comment]
The changes made for v 0.5.0 don't really address the ElastiCache Redis issue. Instead of a blank DB dropdown, now there is a DB dropdown with '0' as the only option, so we still cannot change databases using the UI. By default, ElastiCache Redis parameter groups set the database range to 0-15. I'm guessing that Medis doesn't have an easy way of determining this because ElastiCache Redis disables "CONFIG GET DATABASES". There's at least one way I can think of to determine the database count: use "SELECT n" as part of a binary search, since an error is returned if out of bounds. Not pretty, but it works. At a minimum, if the DB range cannot be determined, the DB dropdown should be 0-15 by default since that is the common case, which should be overridable.

![medis_elasticache_db](https://cloud.githubusercontent.com/assets/3912214/21253925/a3bd9fb8-c327-11e6-88f8-0253ff171a40.png)
.

**Comment by luin** [comment]
Hey @roeyby. Thank you for the feedback! Actually Medis 0.5.0 uses `SELECT` command to guess the database count when `CONFIG` command not returning it. I've tested it with Redis Labs and it worked.

I was wondering whether you can provide a test server on ElastiCache so I can test against it.

**Comment by roeyby** [comment]
Hi @luin. Unfortunately, I don't have the time right now to spin up a test environment for you to debug with, but I thought I would at least show you what happens when you call SELECT and CONFIG in ElastiCache. If that's not sufficient, perhaps we can revisit this issue in the future.
![medis_elasticache_db_select](https://cloud.githubusercontent.com/assets/3912214/21272572/8181c74a-c385-11e6-92c5-71ec032c2096.png)
