### ISSUE TITLE
App Store version is still at 0.6.0

### ISSUE THREAD

**Issue by atellier** [luin/medis#70]
Hi again,

I was checking my version of the paid version (app store) and it is 0.6.0 as of today. I was hoping to get the 0.6.1 since it has that search within sets feature that I needed ;)

Could you please push an update to the app store?

Thanks!

**Comment by luin** [comment]
Hi @atellier, the version on app store (0.6.0) and on the release page (0.6.1) is same. The only different between them are the version number (due to the current build process).

The new feature "support search/find within a key" means you can search inside a string (the value of a STR key or the field of a HASH/SET/ZSET key) by press Command+F.

**Comment by atellier** [comment]
Ok, Thanks....

I thought the "search" was for the sets members - look like this is already a case: https://github.com/luin/medis/issues/54. That'd be awesome indeed
